### PR TITLE
Initial card sizes implementation

### PR DESCRIPTION
**Pull request by fabianluque**
@matt8707 Let me know what you think.

This is a preview:

image

Only 2 sizes for now: Compact and Widget.

Thinking on providing 4 sizes: 

- Compact (your original button size)
- Small (what I call Widget here)
- Medium (Sport scores, Dinner menu, pictures, etc.)
- Large (for something like Camera or Media cards, etc.)

Not all card type need to support all sizes, for example, button only supports Compact and Small, media and camera are currently Medium by default

Good source for inspiration: https://developer.apple.com/design/human-interface-guidelines/widgets

### CODE REVIEW

**Comment by matt8707** [comment]
I like the idea, but it might be too early for for this before you work on this further? Hard coding sizes before mobile support may not be ideal; there should be some kind of responsiveness. I tested it, and the current implementation is not reactive when I change the "size" option. But I do agree that this option should be implemented at some point!

**Comment by fabianluque** [comment]
Yes, reactivity is pending, just wanted to share it before going further with it. Should be easy to fix.

When you say hard coding sizes, what do you mean? Not really sure what your plans are for mobile, if that's something you want out first before exploring card sizes.

**Comment by matt8707** [comment]
> Not really sure what your plans are for mobile

I'm not sure either but @janiskelemen wanted to work on mobile support https://github.com/matt8707/ha-fusion/issues/15#issuecomment-1875897555

> When you say hard coding sizes, what do you mean?

I mean things like this, that value might be different on other screen sizes (I know I did it first but it shoudn't be a store)

```js
export const itemWidth = readable(4.5);
```

**Comment by fabianluque** [comment]
Yeah, was following your lead there regarding width.

I’m open to work on it if you point me in the direction you envision. If you want to wait, that’s totally fine too.

**Comment by matt8707** [comment]
Appreciate it. Let's implement mobile support first

**Pull request closed without merging**
