### PR TITLE
Initial support for card sizes

### PR DESCRIPTION
**Pull request by fabianluque**
Added initial support for different sizes of cards.

For now there's only 2 sizes available: compact and small.  Media and camera can be considered large size (hard coded for now). I think a medium size would be also cool to have. Inspired by iOS widgets: https://developer.apple.com/design/human-interface-guidelines/widgets

Desktop:
image

Mobile (iPhone 15 Pro Max):
image

### CODE REVIEW

**Comment by matt8707** [comment]
Nice!

* Consider using data attributes instead, such as .container[data-size='compact']. This way, the styles don't have to be embedded in js, and we'll benefit from CSS syntax highlighting and auto-completion. [example](https://github.com/matt8707/ha-fusion/blob/5e5ec3efe126f5b95a858d1c2ff89de99940fcad/src/lib/Main/Button.svelte#L477-L480)
* $: size - 'size' is declared but its value is never read.ts(6133)
* The compact buttons now have huge padding/small font. I don't think you should change that.
* It would be nice to have an animation/transition in the preview when changing the size in modal buttonconfig.

**Comment by fabianluque** [comment]
@matt8707 Updated the PR with your suggestions, only thing pending is the animation, I'm not an expert there, any pointers?

**Comment by hjaltij** [comment]
Looks great :)

**Comment by nagtegaal** [comment]
> @matt8707 Updated the PR with your suggestions, only thing pending is the animation, I'm not an expert there, any pointers?

https://pqina.nl/blog/animating-width-and-height-without-the-squish-effect/

**Comment by matt8707** [comment]
Still some weird padding on 'compact'

Also noticed that this breaks camera preview

screenshot

**Comment by fabianluque** [comment]
@matt8707 Updated with fixes for the issues you found.

**Comment by matt8707** [comment]
I'm seeing a lot of issues, unfortunately. Weird padding still exists, 

Skärmavbild 2024-01-10 kl  19 17 47



and using the 'small' size doesn't work when resizing the window. I think it should only be multiples of 'compact', like twice the height, and like a camera, twice the width and four times the height.

screen

**Comment by fabianluque** [comment]
@matt8707 Let me know what you think after the last change.

**Comment by matt8707** [comment]
It introduces issues in too many scenarios, so I'll hold off on this one for now

**Pull request closed without merging**
