### PR TITLE
Weather forecast sidebar component

### PR DESCRIPTION
**Pull request by EvanBarbour3**
### Weather Forecast Sidebar Component

I've added a sidebar component for a weather forecast. I've attached a video of it being configured and displaying, and also a picture of the 3 icon packs I've added as part of the setup.

If there's any changes you'd like let me know

Thanks!

https://github.com/matt8707/ha-fusion/assets/7600557/94d03e3c-4424-4f14-a77e-4ffd1146cc80

Screenshot 2024-01-13 at 21 00 45

### CODE REVIEW

**Comment by matt8707** [comment]
Very nice!

I think it should be horizontally responsive, using something like `justify-content: space-between;` to fit the sidebar width.

Here are some bugs I found in WeatherConfig:

* The page crashes if `entity.attributes.forecast` does not exist.
   - Error: Uncaught (in promise) TypeError: entity.attributes.forecast is undefined.
   - Solution: Check for `forecast` before filtering `$: weatherStates` and use optional chaining.

* The Meteocons icon pack doesn’t work, resulting in a blank fallback.

* The "days to show" feature stops at 6, excluding Saturday.
   - The "days to show" should include the display of [firstDay](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getWeekInfo) if it’s Sunday or Monday.

Skärmavbild 2024-01-14 kl  09 43 28

**Comment by EvanBarbour3** [comment]
Thanks for the feedback

I'll take a look at the Meteocons not loading, I used the static ones and can't currently replicate blanks.

Some things I've noticed with different forecast integrations:
- `OpenWeatherMap` provides it hourly, showing 48 entries (which I believe the screenshot above is using). It can be configured to do it daily too, but requires a paid plan
- `Meteorologisk institutt (Met.no)` provides it daily, showing 6 entries (which includes current date)

I'll take a look at some others and see the behaviour of those too.

I originally had it horizontally responsive until I added in the days to show, but when you change it down to <= 3, it didn't look too correct - I'll see what I can do in terms of this

**Comment by EvanBarbour3** [comment]
@matt8707 I've finished making changes, let me know what you think 😊

**Comment by matt8707** [comment]
Looks good!

**Comment by ajbatchelor** [comment]
Hi - just added this component into the sidebar and getting overlap on icons/dataset. Same result using other forecast entities.  

Also, thanks.  Love this addition very much!

Screenshot 2024-01-24 at 12 17 18 pm


Screenshot 2024-01-24 at 12 14 40 pm

**Comment by EvanBarbour3** [comment]
> Hi - just added this component into the sidebar and getting overlap on icons/dataset. Same result using other forecast entities.
> 
> Also, thanks. Love this addition very much!
> 
> Screenshot 2024-01-24 at 12 17 18 pm
> 
> Screenshot 2024-01-24 at 12 14 40 pm

That issue was fixed in https://github.com/matt8707/ha-fusion/releases/tag/2024.1.8

**Pull request merged**
