### PR TITLE
add year to sidebar

### PR DESCRIPTION
**Pull request by carsten-walther**
add possibility to show or hide year in sidebars date

### CODE REVIEW

**Comment by matt8707** [comment]
Thanks!

* Can you explain why you are setting the HTML language attribute?
* Translations should not be edited manually

**Comment by carsten-walther** [comment]
Some browser will translate the content of the page. I usually use Brave. When I switch to German, the html language attribute stays on en. So the browser will translate the page to German.

**Comment by matt8707** [comment]
Okay, can you make that a separate PR for that?

**Comment by carsten-walther** [comment]
Sure, didn't recognize that this was the same PR. Sorry for that inconvenience.

**Pull request closed without merging**
