### PR TITLE
update mobile support

### PR DESCRIPTION
**Pull request by matt8707**
@janiskelemen, your thoughts?

Updated how nav width (views) are calculated
[more precise way to calc nav width](https://github.com/matt8707/ha-fusion/pull/92/commits/1feecb3d27997be0648cd1f93f57386d715431bf)

Unfortunately I had to revert drawer height, but I got another idea
[drawer height 'auto' breaks animations, revert](https://github.com/matt8707/ha-fusion/pull/92/commits/cc1a2e23e2922c89891ff3528f215ed912ae6693)

With something like this, fitting everything on mobile should be doable
[add dropdown](https://github.com/matt8707/ha-fusion/pull/92/commits/369738bddeb21048cac2ebec3622f1fcde8b25bb)

https://github.com/matt8707/ha-fusion/assets/36163594/ebad291d-8c5c-4988-a600-2df18d564169

### CODE REVIEW

**Comment by janiskelemen** [comment]
Hi @matt8707,

Adding the button width to the calculation makes total sense, I like your improvements on this. 

The dropdown is a good idea especially considering that more buttons might be added in the future 👍

**Comment by janiskelemen** [comment]
Unfortunately, the drawer is now broken on mobile again:
Screenshot 2024-01-05 at 10-40-11@2x

You could add a larger fixed height (double the 4.75rem) only on mobile so it can fit two button rows, and it will keep the  animation working. What do you think?

**Comment by matt8707** [comment]
Thanks, I ended up with a mix of your ideas

**Comment by janiskelemen** [comment]
> Thanks, I ended up with a mix of your ideas

Thanks the drawer works great now! 
Unfortunately, the sidebar toggle is gone now on mobile and the sidebar is always visible. Was that intentional? The camera view in the sidebar is also not responsive anymore.

image

**Comment by janiskelemen** [comment]
Just tested a bit on mobile and I don't think showing the sidebar on top of the main section is a good UX choice. If I open the app on mobile just to turn off a light which I have on my main view I always have to scroll down the whole sidebar which makes the UX not that accessible on mobile. What made you remove the toggle button?

**Comment by Gerrett84** [comment]
The drawer works great -  I Love the Dropdown ☺️



but the sections still doesn't fit on mobile

**Comment by matt8707** [comment]
> Just tested a bit on mobile and I don't think showing the sidebar on top of the main section is a good UX choice. If I open the app on mobile just to turn off a light which I have on my main view I always have to scroll down the whole sidebar which makes the UX not that accessible on mobile. What made you remove the toggle button?

In the previous solution, editing sidebar items on mobile was impossible, and completely hiding the sidebar was clever, but felt wrong. I'm considering either providing the option to hide sidebar items on mobile (like you can disable popups in button config) or adding the sidebar as a view on mobile, so it's far left and not selected by default. You're right in that the sidebar should not be displayed in full unless the user opts for it.

**Comment by Gerrett84** [comment]
> > Just tested a bit on mobile and I don't think showing the sidebar on top of the main section is a good UX choice. If I open the app on mobile just to turn off a light which I have on my main view I always have to scroll down the whole sidebar which makes the UX not that accessible on mobile. What made you remove the toggle button?
> 
> In the previous solution, editing sidebar items on mobile was impossible, and completely hiding the sidebar was clever, but felt wrong. I'm considering either providing the option to hide sidebar items on mobile (like you can disable popups in button config) or adding the sidebar as a view on mobile, so it's far left and not selected by default. You're right in that the sidebar should not be displayed in full unless the user opts for it.

Editing the sidebar was possible by switching to the sidebar and opening the editor mode there. 
Showing the sidebar on mobile as a header with the option to hide items here is a great idea. In addition, I could also easily imagine the option for items to be visible on mobile but not on the desktop.

**Comment by janiskelemen** [comment]
> The drawer works great -  I Love the Dropdown ☺️
> 
> 
> 
> but the sections still doesn't fit on mobile
> 
> 
> 
> 
> 

Off topic:
@Gerrett84 do you mind sharing your weather template in the Custom Templates thread in Discussions? I think this might be  useful for others.
image

**Comment by anarion80** [comment]
@janiskelemen this is an example weather template that results in something similar as @Gerrett84  has:

```yaml
weather: >
          {%- set temperature = states('sensor.openweathermap_temperature') -%}
          {%- set condition = states('sensor.openweathermap_condition') -%}
          {%- set weather_icon = '' -%}
          {%- if condition == 'clear-night' -%} {{ weather_icon }} {{'\U0001F315'}}
          {%- elif condition == 'cloudy' -%} {{ weather_icon }} {{'\U00002601\U0000FE0F'}}
          {%- elif condition == 'exceptional' -%} {{ weather_icon }} {{'\U0001F31E'}}
          {%- elif condition == 'fog' -%} {{ weather_icon }} {{'\U0001F32B\U0000FE0F'}}
          {%- elif condition == 'hail' -%} {{ weather_icon }} {{'\U000026AA'}}
          {%- elif condition == 'lightning' -%} {{ weather_icon }} {{'\U0001F329\U0000FE0F'}}
          {%- elif condition == 'lightning-rainy' -%} {{ weather_icon }} {{'\U000026C8\U0000FE0F'}}
          {%- elif condition == 'partlycloudy' -%} {{ weather_icon }} {{'\U0001F324\U0000FE0F'}}
          {%- elif condition == 'pouring' -%} {{ weather_icon }} {{'\U00002614'}}
          {%- elif condition == 'rainy' -%} {{ weather_icon }} {{'\U00002602\U0000FE0F'}}
          {%- elif condition == 'snowy' -%} {{ weather_icon }} {{'\U00002744\U0000FE0F'}}
          {%- elif condition == 'snowy-rainy' -%} {{ weather_icon }} {{'\U0001F328\U0000FE0F'}}
          {%- elif condition == 'sunny' -%} {{ weather_icon }} {{'\U00002600\U0000FE0F'}}
          {%- elif condition == 'windy' -%} {{ weather_icon }} {{'\U0001F32C\U0000FE0F'}}
          {%- elif condition == 'windy-variant' -%} {{ weather_icon }} {{'\U0001F390'}}
          {%- endif -%}
          {%- set apparent = states('sensor.openweathermap_feels_like_temperature') | round -%}
          {%- set precip = states('sensor.openweathermap_forecast_precipitation_probability') | round -%}
          {%- if not is_state('sensor.openweathermap_temperature', 'unknown') -%}
            {%- if temperature | float(default=0) <= 0.0 -%}
              {{ weather_icon }} Odczuwalna {{ apparent }}° z {{ precip }}% ryzykiem śniegu {{'\u2744\uFE0F'}}
            {%- elif temperature | float(default=0) > 0.0 -%}
              {{ weather_icon }} Odczuwalna {{ apparent}}° z {{ precip }}% ryzykiem deszczu {{ '\u2614\uFE0F' if precip > 30 }}
            {%- endif -%}
          {%- else -%}
            Nie można załadować prognozy pogody...
          {%- endif -%}
```

**Comment by janiskelemen** [comment]
Great thank you @anarion80

I will try it on my sidebar and add it to the Custom Templates thread.

**Pull request merged**
