### PR TITLE
Implemented Cover modal

### PR DESCRIPTION
**Pull request by fabianluque**

### CODE REVIEW

**Comment by matt8707** [comment]
Great!

I'm trying it with demo entities and i get reverse value of slider, do you know why?

```yaml
current_position: 10
friendly_name: Hall Window
supported_features: 15
```

screen

**Comment by fabianluque** [comment]
Yes, tried to mimic HA modals behavior, they show full bar when 0% and empty bar when 100%. This is 100% for example:

image

Can be changed of course, just let me know what makes more sense.

**Comment by matt8707** [comment]
I don't think it's logical for the bar to be filled to 90% while the state indicates 10%. What exactly does 'position' mean? Is position 0 'fully open and not covered,' and position 100 'fully closed/covered'?

**Comment by fabianluque** [comment]
100% is fully open, 0% is fully closed

**Comment by matt8707** [comment]
Okay, at position 100, it is 100% open. At position 0, it is 0% open. 

The confusion seems to arise because they are mimicking the **physical** cover positions in a vertical orientation. I think we should do it like light brightness slider for consistency, unless you have any objections. 😊

**Comment by fabianluque** [comment]
No objections, just pushed an update.

**Comment by matt8707** [comment]
Thanks!

**Pull request merged**
